# Generated by Django 3.2.18 on 2023-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnis',
            name='image',
            field=models.ImageField(upload_to='media/team', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='alumnis',
            name='program',
            field=models.CharField(max_length=256, verbose_name='İştirak etdiyi program'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
