# Generated by Django 3.2.18 on 2023-04-25 13:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/events', verbose_name='Şəkil')),
                ('other_image1', models.ImageField(blank=True, null=True, upload_to='media/events', verbose_name='Əlavə Şəkil 1')),
                ('other_image2', models.ImageField(blank=True, null=True, upload_to='media/events', verbose_name='Əlavə Şəkil 2')),
                ('other_image3', models.ImageField(blank=True, null=True, upload_to='media/events', verbose_name='Əlavə Şəkil 3')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('location', models.CharField(max_length=256, verbose_name='Ünvan')),
                ('description', tinymce.models.HTMLField(max_length=10000, verbose_name='Qısa məzmun')),
                ('time', models.CharField(max_length=256, verbose_name='Zaman')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/news', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(max_length=10000, verbose_name='Qısa məzmun')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/programs', verbose_name='Şəkil')),
                ('other_image1', models.ImageField(blank=True, null=True, upload_to='media/programs', verbose_name='Əlavə Şəkil 1')),
                ('other_image2', models.ImageField(blank=True, null=True, upload_to='media/programs', verbose_name='Əlavə Şəkil 2')),
                ('other_image3', models.ImageField(blank=True, null=True, upload_to='media/programs', verbose_name='Əlavə Şəkil 3')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(max_length=10000, verbose_name='Qısa məzmun')),
                ('time', models.CharField(max_length=256, verbose_name='Zaman')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
