# Generated by Django 3.2.18 on 2023-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='time',
            field=models.CharField(max_length=256, verbose_name='Deadline:'),
        ),
    ]
